# config.yaml
paths:
  prompt_yaml: "./prompt_assets/prompt.yaml"
  prompt_user_query: "./prompt_assets/prompt_user_query.yaml"
  prompt_func_results: "./prompt_assets/prompt_func_results.yaml"
  examples_json: "./prompt_assets/examples.json"
  examples_path: "./prompt_assets/examples"
  curriculum_csv: "./prompt_assets/curriculum.csv"
  results_corrected: "./results/openai_2023-12-29_corrected"
  results_generated: "results/openai_2024-01-06"
  #json_path: "./tools_singleturn.json"
  #json_path: "./tools_multiturn.json"
  json_path: "./dpo_hf_dataset.json"
  dpo_path: "./results/openai_2023-12-29_corrected_dpo"
  redis_schema: "./redis_schema.yaml"
  #hf_dataset_path: "interstellarninja/tool-calls-singleturn"
  hf_dataset_path: "NousResearch/func-calling-singleturn"
  hf_dpo_path: "NousResearch/func-calling-dpo"
  #hf_dataset_path: "interstellarninja/tool-calls-multiturn"
  #hf_dataset_path: "NousResearch/func-calling"
  #hf_dpo_path: "interstellarninja/tool-calls-dpo"
  #hf_dataset_path: "interstellarninja/tool-calls-sharegpt"
